services:
  - type: web
    name: reactjs1-backend
    env: python
    region: oregon
    plan: free
    root: backend
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py

  - type: static_site
    name: reactjs1-frontend
    env: node
    region: oregon
    plan: free
    root: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
